### ISSUE TITLE
Relax nimble_parsec requirement

### ISSUE THREAD

**Issue by cjbottaro** [elixir-cldr/cldr_print#2]
I'm getting this error when running `mix deps.get` on a fairly new Phoenix project.

```
Because "the lock" specifies nimble_parsec 1.3.0 and ex_cldr_print >= 1.0.0 depends on nimble_parsec ~> 0.5, the lock is incompatible with ex_cldr_print >= 1.0.0.
And because your app depends on the lock, ex_cldr_print >= 1.0.0 is forbidden.
So, because your app depends on ex_cldr_print ~> 1.0, version solving failed.
** (Mix) Hex dependency resolution failed
```

Adding this seems to fix things...
```elixir
{:nimble_parsec, "~> 1.3", override: true},
```

Thanks!

**Comment by kipcole9** [comment]
Thanks for the report. Fixed and published as [ex_cldr_print 1.0.1](https://hex.pm/packages/ex_cldr_print/1.0.1). The changelog entry is:

### Enhancements

* Relax `nimble_parsec` requirement. Thanks to @cjbottaro. Closes #2.

* Fix configuration of the default cldr backend.
*
